spring.application.name=appointment-scheduler

# Connection String (This creates a file named 'database.db' in your project root)
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate Dialect for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Also, ensure Hibernate doesn't try to drop/create tables after data is inserted
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=never